### ISSUE TITLE
Stable version.

### ISSUE THREAD

**Issue by ZhukV** [Gregwar/CaptchaBundle#115]
Hi.
Please create a stable version (new tag revision) of this package for next download via composer.

Thank.

**Comment by Gregwar** [comment]
Tagged 1.0.12 for both Captcha & CaptchaBundle
Can you confirm it's OK,

**Comment by ZhukV** [comment]
Why not create 2.0.* as stable, because now working in 2.0-dev.

**Comment by Gregwar** [comment]
Actually, I would only go to `2.0` if there was major refactoring or enancements

**Comment by cordoval** [comment]
you are good as long as you keep bumping the lower number often

**Comment by cordoval** [comment]
the last bugfix for instance is screaming for a tagging

**Comment by Gregwar** [comment]
Maybe I should have a look to your PRs before :wink:

**Comment by Gregwar** [comment]
Ok, now tagged `v1.1` for both Captcha & CaptchaBundle
Can you confirm it's ok?

**Comment by cordoval** [comment]
of course, yes since you have responded promptly i will do this now

**Comment by cordoval** [comment]
versions look good

project using them works like a charm :astonished:

**Comment by cordoval** [comment]
close please

**Comment by Gregwar** [comment]
Thx
