### ISSUE TITLE
Enhancement: Captcha Field Twig Overrides

### ISSUE THREAD

**Issue by ReservedDeveloper** [Gregwar/CaptchaBundle#119]
As a possible future enhancement, it would be nice to see this bundle provide a custom Twig block for rendering the captcha text input. This would allow us to add overrides (ex: custom classes) before being passed along to the default `form_widget_simple` block.

**Comment by Gregwar** [comment]
Actually, you can already override the captcha_field block I guess

**Comment by ReservedDeveloper** [comment]
You know, I even looked at `Gregwar/CaptchaBundle/Resources/views/captcha.html.twig`. What I didn't do was look on line 16: `{{ form_widget(form) }}`. Sorry about that! Closing now.

**Comment by Gregwar** [comment]
No problem :-)
