### ISSUE TITLE
Error with imagettfbbox()

### ISSUE THREAD

**Issue by pgbonino** [Gregwar/CaptchaBundle#121]
I know this error has nothing to do with the bundle itself, but I felt It would be a good idea to post it here.

After having installed the CaptchaBundle following the instructions, the first time I use it, I get the following error:

Fatal error: Call to undefined function Gregwar\CaptchaBundle\Generator\imagettfbbox() in /Users/pgbonino/Sites/preparatest/vendor/bundles/Gregwar/CaptchaBundle/Generator/CaptchaGenerator.php on line 176

My phpinfo informs this:

gd

GD Support	enabled
GD Version	bundled (2.1.0 compatible)
GIF Read Support	enabled
GIF Create Support	enabled
JPEG Support	enabled
libJPEG Version	9 compatible
WBMP Support	enabled
XBM Support	enabled

So, apparently the GD module is correctly loaded.

Any idea on the error I am getting?

**Comment by Gregwar** [comment]
Hello
What version are you using?
There is normally no call to this method from this file, since rhe captcha generation logic has moved to gregwar/captcha a while ago
Did you cloned this repository with composer?

**Comment by pgbonino** [comment]
Hello.
Thank you for your answer
Yep, I forgot to mention versions. 
I am using Symfony2.0, so installed the Captcha 2.0 branch, as indicated in the instructions.
No, I didn't use composer. Just GIT

**Comment by pgbonino** [comment]
Forget it... I know it is not an issue to do with your bundle. Better close it. If you'd like to help, you can check this post in Stackoverflow "http://stackoverflow.com/questions/29402642/how-can-i-correctly-configure-gd-support-for-php-i-am-getting-an-error-calling", where more details are being given. Thanks a lot!!
