### ISSUE TITLE
BROKEN

### ISSUE THREAD

**Issue by sebastienvermeille** [Gregwar/CaptchaBundle#129]
Bundle is broken on production :

Twig_Error_Loader: The "E:\BitBucket\aaa\vendor\gregwar\captcha-bundle\Gregwar\CaptchaBundle/Resources/views" directory does not exist. in E:\BitBucket\Laaa\vendor\twig\twig\lib\Twig\Loader\Filesystem.php on line 93

**Comment by Gregwar** [comment]
May be a psr-4 related issue
Ping @cordoval ?

**Comment by Gregwar** [comment]
Can you clear your cache and try again?

**Comment by sebastienvermeille** [comment]
I swapped back to 1.0.12 and it worked. (My cache is cleared after each deploy so it was not the cause and another guy came on #symfony-fr last week to talk about the same bug)

**Comment by cordoval** [comment]
@sebastienvermeille i think this should be easily trackable, did you also rm -rf vendor?
the  error you show clearly tells me you are still not upgraded

**Comment by speedy001** [comment]
I saw that captcha is broken now if as_url is false. On dev-master captcha.html.twig you give something like this:

src="{{ captcha_code }}?n={{ 'now'|date('U') }}"

befor was:

src="{{ captcha_code }}"

and all work good if we render captcha with as_url = true but when I change on false captcha don't render a image.

**Comment by Gregwar** [comment]
@speedy001 I've fixed this issue introduced by #128 that broken the inlined captchas
@sebastienvermeille issue is however not the same
