### ISSUE TITLE
Usage of "pattern" in routing.yml

### ISSUE THREAD

**Issue by iltar** [Gregwar/CaptchaBundle#135]
As of Symfony 2.7, deprecations are being thrown in places where code will be removed. One of those deprecations is the usage of `pattern` in the routing config.

```
DEPRECATED - The "pattern" option in file "/vendor/gregwar/captcha-bundle/Resources/config/routing/routing.yml" is deprecated since version 2.2 and will be removed in 3.0. Use the "path" option in the route definition instead.
```

`routing.yml`

```
gregwar_captcha.generate_captcha:
    pattern:        /generate-captcha/{key}
    defaults:       { _controller: GregwarCaptchaBundle:Captcha:generateCaptcha }
```

`pattern` should be replaced with `path`. However, this fix will break symfony 2.1 as this deprecation is of 2.2 and higher. This brings another issue: Should Symfony 2.1 still be supported? The currently maintained symfony versions are 2.3, 2.6 and 2.7.

I could write a pull request but that means 2.1 would no longer be supported.

**Comment by fkrauthan** [comment]
I would say 2.1 should not longer be supported and the routing file changed.

**Comment by Gregwar** [comment]
Ok so this will break <=2.1 bc?

**Comment by Gregwar** [comment]
I guess this bundle can stop supporting so old versions
I may add a tag before doing that

**Comment by StudioMaX** [comment]
@Gregwar So, what do you think about upgrading to the 2.3 version?

**Comment by tombevers** [comment]
As Symfony 3.0 is out this is a problem for upgrading or starting a new project when using this bundle.
