### ISSUE TITLE
Supporting Symfony3

### ISSUE THREAD

**Issue by Raphy** [Gregwar/CaptchaBundle#148]
Any information about supporting Symfony3 ?

**Comment by nslocomotives** [comment]
Agreed, Im trying to get ahead with my homepage development showcasing some of my work with symfony, and symfony3 support for a Captcha bundle would be epic :-)

**Comment by Gregwar** [comment]
Now using `::class` makes it work with sf3
Can you confirm it's OK?
(I also tagged)

**Comment by nslocomotives** [comment]
Composer wont install it  as a dependency fail:

Nigels-iMac:nslocomotives nigelsmith$ composer require gregwar/captcha-bundle v1.0.13
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for gregwar/captcha-bundle v1.0.13 -> satisfiable by gregwar/captcha-bundle[v1.0.13].
    - Conclusion: remove symfony/symfony v3.0.0
    - Conclusion: don't install symfony/symfony v3.0.0
    - gregwar/captcha-bundle v1.0.13 requires symfony/form ~2.1 -> satisfiable by symfony/form[v2.1.0, v2.1.1, v2.1.10, v2.1.11, v2.1.12, v2.1.13, v2.1.2, v2.1.3, v2.1.4, v2.1.5, v2.1.6, v2.1.7, v2.1.8, v2.1.9, v2.2.0, v2.2.1, v2.2.10, v2.2.11, v2.2.2, v2.2.3, v2.2.4, v2.2.5, v2.2.6, v2.2.7, v2.2.8, v2.2.9, v2.3.0, v2.3.1, v2.3.10, v2.3.11, v2.3.12, v2.3.13, v2.3.14, v2.3.15, v2.3.16, v2.3.17, v2.3.18, v2.3.19, v2.3.2, v2.3.20, v2.3.21, v2.3.22, v2.3.23, v2.3.24, v2.3.25, v2.3.26, v2.3.27, v2.3.28, v2.3.29, v2.3.3, v2.3.30, v2.3.31, v2.3.32, v2.3.33, v2.3.34, v2.3.35, v2.3.4, v2.3.5, v2.3.6, v2.3.7, v2.3.8, v2.3.9, v2.4.0, v2.4.1, v2.4.10, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.4.7, v2.4.8, v2.4.9, v2.5.0, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9, v2.6.0, v2.6.1, v2.6.10, v2.6.11, v2.6.12, v2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9, v2.7.0, v2.7.1, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.8.0].
    - don't install symfony/form v2.1.0|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.1.1|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.1.10|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.1.11|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.1.12|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.1.13|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.1.2|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.1.3|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.1.4|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.1.5|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.1.6|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.1.7|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.1.8|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.1.9|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.2.0|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.2.1|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.2.10|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.2.11|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.2.2|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.2.3|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.2.4|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.2.5|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.2.6|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.2.7|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.2.8|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.2.9|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.3.0|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.3.1|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.3.10|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.3.11|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.3.12|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.3.13|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.3.14|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.3.15|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.3.16|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.3.17|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.3.18|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.3.19|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.3.2|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.3.20|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.3.21|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.3.22|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.3.23|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.3.24|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.3.25|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.3.26|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.3.27|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.3.28|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.3.29|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.3.3|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.3.30|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.3.31|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.3.32|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.3.33|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.3.34|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.3.35|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.3.4|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.3.5|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.3.6|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.3.7|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.3.8|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.3.9|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.4.0|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.4.1|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.4.10|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.4.2|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.4.3|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.4.4|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.4.5|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.4.6|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.4.7|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.4.8|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.4.9|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.5.0|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.5.1|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.5.10|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.5.11|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.5.12|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.5.2|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.5.3|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.5.4|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.5.5|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.5.6|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.5.7|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.5.8|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.5.9|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.6.0|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.6.1|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.6.10|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.6.11|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.6.12|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.6.2|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.6.3|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.6.4|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.6.5|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.6.6|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.6.7|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.6.8|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.6.9|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.7.0|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.7.1|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.7.2|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.7.3|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.7.4|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.7.5|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.7.6|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.7.7|don't install symfony/symfony v3.0.0
    - don't install symfony/form v2.8.0|don't install symfony/symfony v3.0.0
    - Installation request for symfony/symfony 3.0.* -> satisfiable by symfony/symfony[v3.0.0].


Installation failed, reverting ./composer.json to its original content.
Nigels-iMac:nslocomotives nigelsmith$

**Comment by Gregwar** [comment]
Ok, can you try again?

**Comment by nslocomotives** [comment]
Epic, Its downloaded, ill now include it in my mailer form. :-)  Ill let you know how it goes.

**Comment by nslocomotives** [comment]
Fantastic, speedy response and its working a treat in symfony3 :-)

**Comment by Raphy** [comment]
Nice! Care, using `class` keyword for the classname resolution is only available since PHP 5.5 and the composer.json requires only PHP from 5.3 that can make incompatibilities in some case.
[PHP Official Documentation about `static` keyword](http://php.net/manual/en/language.oop5.basic.php#language.oop5.basic.class.class)

**Comment by idciconsulting** [comment]
I think you have to change the tag verions.
Now your dev-master branch is not working with php5.3 !
So to allow older project to keep working with, remove tag v1.0.13 and create a v2.0.0 (or v1.2.0)

Like this the v1.0.x and 1.1.x will working with php5.3 and upper
and the 2.x and comming versions will works for php5.5 and upper

**Comment by Gnucki** [comment]
If you follow [semver spec](http://semver.org/) (as Symfony do), this should be a 2.0.

**Comment by idciconsulting** [comment]
Agree with Gnucki

**Comment by Sander-Toonen** [comment]
Seems like this commit breaks compatibility with older Symfony versions.
See: http://stackoverflow.com/q/34204066/3492835

**Comment by jakenoble** [comment]
+1 broken for me on Symfony 2.7.7 using `::class` but works with `'captcha``

**Comment by Gregwar** [comment]
OK, one solution should be adding to the readme that for version `<2.8` of symfony they should require version `<1.0.13` of CaptchaBundle
Does it seems right?

**Comment by Gnucki** [comment]
> Patch version Z (x.y.Z | x > 0) MUST be incremented if only backwards compatible bug fixes are  introduced. A bug fix is defined as an internal change that fixes incorrect behavior.

> Minor version Y (x.Y.z | x > 0) MUST be incremented if new, backwards compatible functionality is introduced to the public API. It MUST be incremented if any public API functionality is marked as deprecated. It MAY be incremented if substantial new functionality or improvements are introduced within the private code. It MAY include patch level changes. Patch version MUST be reset to 0 when minor version is incremented.

> Major version X (X.y.z | X > 0) MUST be incremented if any backwards incompatible changes are introduced to the public API. It MAY include minor and patch level changes. Patch and minor version MUST be reset to 0 when major version is incremented.

If you follow this spec (followed by Symfony), as I said, it should be a 2.0.
At least a 1.1 or 1.2 in my opinion if you do not want to follow this spec.
A paragraph in the documentation seems to me a bit insufficient. Normally, the version is the tool to handle this kind of things.

**Comment by Gregwar** [comment]
OK, removed tag 1.0.13, tagged 2.0 and explained in the README/
https://github.com/Gregwar/CaptchaBundle/#compatibility-with-symfony

Does it sounds good?

**Comment by Sander-Toonen** [comment]
Sounds good :) Thanks

**Comment by Gnucki** [comment]
Perfect! Thanks.

**Comment by StudioMaX** [comment]
It is possible to be BC with older Symfony versions using form helper like this
https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Util/LegacyFormHelper.php
and then use it in the Form builder
``
$builder->add('captcha', LegacyFormHelper::getType('CaptchaType'));
``

**Comment by idciconsulting** [comment]
@jakenoble : I think that you use a PHP version less than 5.5, it's not a Symfony BC but a PHP BC.
@Gregwar : The solution sound good. For the documentation specified that it's a php BC. So less than php5.5 use the bundle version under 2.0, equal or upper to php5.5 could use the bundle version dev-master or until 2.0.

**Comment by Gregwar** [comment]
Actually, i think sf2.8 implies php5.5 since ::class is the new standard for forms in the doc, right?

**Comment by Gregwar** [comment]
(Thus, if you are under 5.5 you can't use 2.8 anyway)

**Comment by Gnucki** [comment]
It does not seem to be the case if you look at [dependencies](https://packagist.org/packages/symfony/symfony#v2.8.0) of `2.8`.

**Comment by Sander-Toonen** [comment]
Well, Symfony 2.8 still supports the old way of defining form fields. So 5.5 is not a dependency for Symfony 2.8. It does become a dependency for your own package when you actually use the ::class construction.

**Comment by StudioMaX** [comment]
Which reason of using
``
$builder->add('captcha', CaptchaType::class);
``
instead of simple
``
$builder->add('captcha', 'Gregwar\CaptchaBundle\Type\CaptchaType');
``
? And use LegacyFormHelper from my previous comment for getParent?

**Comment by Gregwar** [comment]
Actually, I also prefer the alias way for defining form types, I think the new one is verbose and painful
You are right about putting the complete class name, this could be a solution

For getParent, it could simply be
`return 'Symfony\Component\Form\Extension\Core\Type\TextType';`

Which sould be both compatible with 2.8 (w/ php 5.3.9+) and 3.0

**Comment by Gregwar** [comment]
However, @StudioMaX note that the official Symfony form doc (http://symfony.com/doc/2.8/book/forms.html) reffer to the ::class syntax (even if you're not forced to use it since it indeed depends on >=5.3.9)

**Comment by Gregwar** [comment]
I've pushed `v2.0.1` that supports symfony `2.8` with `php>=5.3.9`
It's explained here:
https://github.com/Gregwar/CaptchaBundle/#usage

And `getParent` use the full class name for text type:
https://github.com/Gregwar/CaptchaBundle/blob/f06ff4d2c2d5aabe681f027ee179ac91fbda0e33/Type/CaptchaType.php#L144

**Comment by Gregwar** [comment]
(Also changed the composer dependency with php to  `<5.3.9`)
Is it OK?

**Comment by DarkSoully** [comment]
@Gregwar 
I changed the hole file so i fixed the error on GetParent but now i get this error:

Catchable Fatal Error: Argument 2 passed to Gregwar\CaptchaBundle\Type\CaptchaType::__construct() must be an instance of Gregwar\CaptchaBundle\Generator\CaptchaGenerator, array given, called in /home/dylan/Documents/GitRepos/webandmobile/WebProjectSym/var/cache/dev/appDevDebugProjectContainer.php on line 349 and defined 

And i have no idee what i am doing wrong

**Comment by ZajdeR** [comment]
To work with Symfony3 there should be changed also: 
"getName() " to => "getBlockPrefix()"


UPGRADE-3.0.md
"The getBlockPrefix() method was added to the FormTypeInterface in replacement of the getName() method which has been has been removed."

**Comment by Gregwar** [comment]
I guess this would break Sf2.8 bc, right?

**Comment by ZajdeR** [comment]
Yes, you're right.

**Comment by hackzilla** [comment]
Nothing wrong with getName() calling getBlockPrefix() to maintain compatibility.

**Comment by Gregwar** [comment]
@hackzilla you're right, would you mind PRing?

**Comment by hackzilla** [comment]
Added PR #163
