### ISSUE TITLE
Could not load type "Gregwar\CaptchaBundle\Type\CaptchaType"

### ISSUE THREAD

**Issue by amdouni** [Gregwar/CaptchaBundle#152]
Hello, I nedd your help please,

I've installed Gregwar Captcha wit composer and followed the docs for te config. But when I try to render a form I receive this message : Could not load type "Gregwar\CaptchaBundle\Type\CaptchaType"

Type code : 
use Gregwar\CaptchaBundle\Type\CaptchaType;

class InscriptionType extends AbstractType
{

    // email, nom, prenom, ReCaptcha, offre de parrainage, message
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('captcha', CaptchaType::class)
Please notice that wen I put 'captcha' instead of CaptchaType::class the message becomes : Could not load type "Symfony\Component\Form\Extension\Core\Type\TextType" 

AppKernel
class AppKernel extends Kernel
{
    public function registerBundles()
    {
        $bundles = array(
            new Symfony\Bundle\FrameworkBundle\FrameworkBundle(),
            new Symfony\Bundle\SecurityBundle\SecurityBundle(),
            new Symfony\Bundle\TwigBundle\TwigBundle(),
            new Symfony\Bundle\MonologBundle\MonologBundle(),
            new Symfony\Bundle\SwiftmailerBundle\SwiftmailerBundle(),
            new Symfony\Bundle\AsseticBundle\AsseticBundle(),
            new Doctrine\Bundle\DoctrineBundle\DoctrineBundle(),
            ...
            new Gregwar\CaptchaBundle\GregwarCaptchaBundle()

config.yml
gregwar_captcha: ~

composer show -i |grep gregwar
Warning: This development build of composer is over 60 days old. It is recommended to update it by running "/usr/local/bin/composer self-update" to get the latest version.
gregwar/captcha                      v1.1.1  Captcha generator
gregwar/captcha-bundle               v1.1    Captcha bundle

php app/console --version
Symfony version 2.7.3 - app/dev/debug

Thank you,

**Comment by amdouni** [comment]
I've just upgraded to symfony2.8+ and it works just fine !! I think there is a beak somewhere when using the bundle under 2.7 version. Thank you anyway.

**Comment by Gregwar** [comment]
Actually you can also use older versions of sf but you should depend on older versions of this bundle as explained in the readme
