### ISSUE TITLE
symfony3

### ISSUE THREAD

**Issue by ami-m** [Gregwar/CaptchaBundle#176]
will the bundle be adjusted for symfony3?

**Comment by Gregwar** [comment]
Whats wrong?
I tested it under 3.3 a few days ago and it seems ok

Le mar. 3 oct. 2017 20:58, Ami Malimovka <notifications@github.com> a
écrit :

**Comment by ami-m** [comment]
really? then maybe I'm doing something wrong... I get deprecation notices.
I'll check again, and close the issue if it's on my end.

Thanks for the quick reply though! :)

**Comment by ami-m** [comment]
my mistake I was on an old version. upgraded to 2.0.3 and everything looks ok now.
thanks :-)
