### ISSUE TITLE
Release for symfony 4.x compataible

### ISSUE THREAD

**Issue by andreybolonin** [Gregwar/CaptchaBundle#182]
<img width="578" alt="screen shot 2018-01-06 at 5 23 41 pm" src="https://user-images.githubusercontent.com/2576509/34641042-6d127f78-f306-11e7-9b02-8880574c14e7.png">

@Gregwar can you create a new release? 
wich include https://github.com/Gregwar/CaptchaBundle/pull/180
thx

**Comment by iltar** [comment]
Not sure why you closed this, it's not released yet ;)

@Gregwar any chance you could provide a release with the compatibility fixes? It's a blocker to go to 4.0 for my application (and 3.4 is spamming deprecations in my logs).

**Comment by vchebotarev** [comment]
ping
To my mind it shouldn't be closed ... and there is still no release
