### ISSUE TITLE
What about php7.2 support

### ISSUE THREAD

**Issue by vipinbose** [Gregwar/CaptchaBundle#188]
I am getting an error like the following 
Warning: count(): Parameter must be an array or an object that implements Countable

in vendor/gregwar/captcha/CaptchaBuilder.php at line 333  

 $x = ($width - $textWidth) / 2;
        $y = ($height - $textHeight) / 2 + $size;
---> error here (333)        if (!count($this->textColor)) {
            $textColor = array($this->rand(0, 150), $this->rand(0, 150), $this->rand(0, 150));
        } else {

Any solution for this
Thanks and Regards

**Comment by mbourqui** [comment]
A solution can be found here: Gregwar/Captcha/pull/58

**Comment by vipinbose** [comment]
Thanks
