### ISSUE TITLE
Old format of twig injection

### ISSUE THREAD

**Issue by alexwolf1975** [Gregwar/CaptchaBundle#189]
In GregwarCaptchaExtension we find "GregwarCaptchaBundle::captcha.html.twig" instead of "@ GregwarCaptcha/captcha.html.twig". That cause problem with Symfony 3 and 4. It make impossible using of bundle templates of user project.

**Comment by secit-pl** [comment]
@alexwolf1975 try dev-master

**Comment by Gregwar** [comment]
I belive @secit-pl is right, see #192
