### ISSUE TITLE
Type error: Too few arguments to function Gregwar\CaptchaBundle\Type\CaptchaType::__construct(), 0 passed in C:\xampp\htdocs\Web3\vendor\symfony\symfony\src\Symfony\Component\Form\FormRegistry.php on line 92 and exactly 4 expected

### ISSUE THREAD

**Issue by MortalKonga** [Gregwar/CaptchaBundle#211]
I followed the guide to the letter. What am I doing wrong?

**Comment by Gregwar** [comment]
Can you tell what was wrong ?

**Comment by MortalKonga** [comment]
> 
> 
> Can you tell what was wrong ?

I'm really sorry. Bundle registration was commented in AppKernel.php by a coworker who was trying another captcha bundle.

**Comment by VinGit67** [comment]
Thank you, thank you, thank you !
I had the same problem, and unable to find any solution anywhere.

Thanks to your comment I came upon the idea to look into bundles.php and found that the bundle wasn't registered there...
adding "Gregwar\CaptchaBundle\GregwarCaptchaBundle::class => ['all' => true]" " did the trick !

My weekend will look much better now ;-)

**Comment by Anyeos** [comment]
Same problem here. I think it must be documented that some other captchas can interfere on the installation of this one.

**Comment by Gregwar** [comment]
Hello,
Actually, this problem is already fixed, it was caused by the fact that the package type on composer was not specified as `symfony-bundle`, only I didn't re-tagged any version since then

I tagged `v2.1.2` and installation should be OK now when using `composer req gregwar/captcha-bundle`
