### ISSUE TITLE
Multiple captcha in one page

### ISSUE THREAD

**Issue by jroussay** [Gregwar/CaptchaBundle#215]
Hello,

Is there a way to use multiple captcha in a page, in two separate forms ?

Johan

**Comment by Gregwar** [comment]
Yes, this was introduced by https://github.com/Gregwar/CaptchaBundle/pull/172/
You should use different `session_key` options to ensure the storage of phrases

**Comment by Gregwar** [comment]
Can you confirm it's OK so that I can add some information in the README file about this

**Comment by jroussay** [comment]
It's working, thanks a lot for your support.

Johan
