### ISSUE TITLE
CaptchaType

### ISSUE THREAD

**Issue by gerMdz** [Gregwar/CaptchaBundle#226]
deprecation 

Symfony 5.4.1
gregwar/captcha-bundle: 2.1.5 

Since symfony/framework-bundle 5.3: The "session" service and "SessionInterface" alias are deprecated, use "$requestStack->getSession()" instead. It is being referenced by the "gregwar_captcha.type" service.

Hi. Is there a way to fix it without touching the vendor class?

**Comment by Gregwar** [comment]
Hello
This is done, tagged `v2.1.7`

**Comment by Gregwar** [comment]
Thanks for reporting

**Comment by gerMdz** [comment]
Thank you for your time

**Comment by bretrzaun** [comment]
This drops Symfony 4 compatiblity :-(

**Comment by Gregwar** [comment]
You are right, we should adjust the table here accordingly:
https://github.com/Gregwar/CaptchaBundle#compatibility-with-symfony

Can you confirm it's ok if you use `v2.1.5` ?

**Comment by bretrzaun** [comment]
`v2.1.5` works fine.

Doing this in a bugfix release is probably not a good idea. This would prevent you from creating further fixes for Symfony-4-
compatible versions.

**Comment by Gregwar** [comment]
Ok, here is what I suggest:
- Remove `v2.1.6` and `v2.1.7` tags
- Tag `v2.2` with Sf updates, and update `composer.json` to drop Symfony 4
  - I guess changing `"symfony/framework-bundle": "~4.0|~5.0"` to "symfony/framework-bundle": "~5.0|~6.0"` is ok ?
- Update README table

Does it sounds good to you ?

**Comment by bretrzaun** [comment]
Yes - sound good to me.

**Comment by Gregwar** [comment]
Ok it's done, now on `v2.2.0`

**Comment by Gregwar** [comment]
(Plus edited `composer.json`)
If you can give it a try, tell me if it installs correctly on Sf4

**Comment by bretrzaun** [comment]
https://github.com/Gregwar/CaptchaBundle/blob/v2.2.0/composer.json still allows Symfony 4, so it still updates to that version.

**Comment by Gregwar** [comment]
You are right
It should be fine now, I bumped `v2.2.0` that is no longer compatible with Sf4 and removed irrelevant versions from packagist as well
