### ISSUE TITLE
Symfony 2.3.9 form is not validating Gregwar captcha code

### ISSUE THREAD

**Issue by hoannv** [Gregwar/CaptchaBundle#79]
$builder
            ->add('name', 'text', array(
                'required' => true,
                'label' => 'Your Name'
            ))
            ->add('email', 'email', array(
                'required' => true,
                'label' => 'Your Email'
            ))
            ->add('message', 'textarea', array(
                'required' => true,
                'label' => 'Your Message',
            ))
            ->add('captcha', 'captcha', array(
                'label'    => 'Enter Captcha',
                'required' => false,
                'invalid_message' => 'The captcha code is invalid.'
            ));

This is my form. When I fill all field and submit, no error is found. But form is invalid.

When I remove captcha field, and fill then submit. Form is valid.

Can you tell me what issue happens ?

**Comment by rubab** [comment]
I am using this bundle on Symfony 2.3.30 I added captach type in FormType as 
$builder->add('captcha', 'captcha');
and in php template 
<?php echo $view['form']->widget($contactForm['captcha']) ?>
but captcha image is not rendering.
I installed this bundle via composer.
