### ISSUE TITLE
Performance bottleneck with distortion

### ISSUE THREAD

**Issue by jstoeffler** [Gregwar/CaptchaBundle#83]
Hi,

I've just implemented this bundle in an app of mine. I noticed that the paged rendering was significantly slower, so I did some profiling: http://imgur.com/T82ibjr

The image distortion is very expensive. I did some load testing on a real server and here are the results :

With distortion (blue: number of clients, green: load time): http://imgur.com/rAUXG0P

Without distortion (blue: number of clients, green: load time): http://imgur.com/ZtWvzaE

The load time is stable without distortion, but it's really not scalable with distortion enabled.

I'm using quite big captchas with hight jpeg quality: 

    gregwar_captcha:
        quality: 60
        background_color: [217, 237, 248]
        height: 90
        width: 260
        charset: abcdefhjkmnptuvwxy234689

Is that a known issue? Do you have any idea on how this could be improved?

**Comment by cordoval** [comment]
bump @jstoeffler ?

**Comment by jstoeffler** [comment]
@jstoeffler has moved to other things, sorry :(
