### ISSUE TITLE
Bug - Image shown is different than $expectedCode

### ISSUE THREAD

**Issue by iltar** [Gregwar/CaptchaBundle#97]
I have no idea what exactly causes this, but some times when testing, I notice that when I fill in the image correctly, I have an error saying that it's invalid.

The `$expectedCode` isn't equal to `$form->getData()` and mostly happens after testing the same form a couple of times. I can only fix this with a hard page reload or a manual press on "renew". The return is not null, it's an actual different code than show in the image.

My configuration:
```
gregwar_captcha:
    quality:          100
    distortion:       false
    height:           65
    width:            270
    reload:           true
    as_url:           true
    interpolation:    true
    background_color: [255, 255, 255]
```

**Comment by i--storm** [comment]
Confirn problem. I use captcha with login form. Near 2% of submissions finish with wrong captcha value. In logs I see that captcha in session is completely unmatched with user entered one.
I have this problem on production server with nginx and sessions stored in database. On dev server with apache and sessions in files it never appeared.

**Comment by Gregwar** [comment]
@i--storm do you experience issue when using directly your browser?
What is your 2%? It is possible that bots or people simply fail entering captcha?

**Comment by iltar** [comment]
I seem to have this issue far less now that we are using symfony 2.6, probably do to the SaveSessionListener. It's still occurring, especially for expired sessions.

**Comment by i--storm** [comment]
@Gregwar  My users reporting this problem quiet often. I myself couldn't catch it. May be my system config or network does not promote to such kind of error.
2% from all form submissions has such issue. While there is near 5-6% form submissions has wrong captcha. So, near 30% of cases of wrong captcha represents discussed issue.
It is not wrong reading of captcha image by himan, because some symbols should be right in such case, but captcha entered completely differs from expected.
Here is part of my log:
https://dl.dropboxusercontent.com/u/37273979/Captcha/captcha_errors.txt


It seems for that session id changes somewhere between three requests
1. Form page request
2. Captcha image request
3. Form submission reuest
I'm thinking on problem how to catch this three requests in one log

**Comment by i--storm** [comment]
@iltar do you using standard session storage or PDO?

**Comment by iltar** [comment]
@i--storm PDO, but a somewhat sf1 compatible version ;)

I know it is related to session concurrency in a lot of cases.

**Comment by Gregwar** [comment]
I note you all use as_url method
Whay can basically happen is that the client browser decide whether to cache a previous image or requesting it twice for some reasons.
Could you try using embedded images?
I don't think its compatible with some browsers however (namely IE)

**Comment by i--storm** [comment]
@Gregwar embedded images causes high load to server io system. I've added random string to image url template to prevent browser caching. It didn't help.
Here is example of my img src:
src="{{ captcha_code }}?{{ twig_md5(random(999999)) }}"

**Comment by i--storm** [comment]
found a decision for me:
In template I store captcha URL not in image SRC attribute, then after full page load I add src arttribute value by jquery. I've got rid of this error.

**Comment by Gregwar** [comment]
@i--storm that's strange you have to do this
Is there any other script that would interfer with your images?

**Comment by iltar** [comment]
@Gregwar That's not strange at all. It's most likely still session concurrency. @i--storm what symfony version are you using?

The problem is that the page rendering the form didn't finish saving the session at the moment the image is being loaded on the second request. Saving a session happens on the end of the end of the end of your request, unless you do it manually. In 2.6 a `SaveSessionListener` has been added to make sure the session is saved when the response is send.

**Comment by i--storm** [comment]
@iltar  I think that you are right in version with session concurrency. I'm using sf2.5 and I had another type of problems related to session concurrency. I've solved them by adding this line to app.php:
//....
session_write_close(); // Writes session to database
$response->send();
//...

It solved that problems, but it didn't help with captcha.

@Gregwar no. I don't think so. There is no ajax requests or any other unusual scripts in project. I think same way as @iltar. Our session server may have a delay up to 2-3 seconds while writing session. So it cause the case when captcha request comes before the main page request creates session. I'm planning to migrate to redis in session storage. May be it will solve that kind of problems generally
